Add outreachy'22 wrap-up blog
conda-forge/blog pull request #57
Opened 2022-08-19 14:51 UTC by ssurbhi560

Adding the outreachy wrap-up blog with a brief description of all the tickets that were solved during the internship.

2022-08-24 21:44 UTC, ssurbhi560 commented
Hi @jaimergp, the blog is done! :)

2022-08-25 08:26 UTC, jaimergp approved these changes
I fixed a little issue with the CI, and added a couple of (optional) suggestions for the text. LGTM!

Pinging @conda-forge/core and @kathatherine in case anybody else wants to take a look.

2022-08-25 08:26 UTC, jaimergp commented on posts/2022-08-19-outreachy-wrap-up-blog-2022.rst
> +I am `Surbhi <https://github.com/ssurbhi560>`__, an outreachy intern with conda-forge for the May-August 2022 cohort and I worked on documenting the conda-forge ecosystem.
```suggestion
I am `Surbhi <https://github.com/ssurbhi560>`__, an Outreachy intern with conda-forge for the May-August 2022 cohort and I worked on documenting the conda-forge ecosystem.
```

2022-08-25 08:26 UTC, jaimergp commented on posts/2022-08-19-outreachy-wrap-up-blog-2022.rst
> +        Currently, the documentation regarding the security considerations of conda-forge builds is scattered throughout the documentation, and therefore it is hard to find and read it. With this iss
```suggestion
        Currently, information regarding the security considerations of conda-forge builds is scattered throughout the documentation, and therefore it is hard to find and read. With this issue, we will put all the information together in one place, which will help maintainers and users to know more about how conda-forge secures its packages and infrastructure.
```

2022-08-25 08:27 UTC, jaimergp commented on posts/2022-08-19-outreachy-wrap-up-blog-2022.rst
> +  :redirect: 2022/08/19/outreachy-wrap-up-blog-2022
```suggestion
.. post:: 2022-08-26
  :tags: Outreachy
  :author: Surbhi Sharma
  :redirect: 2022/08/26/outreachy-wrap-up-blog-2022
```

Let's fix the date (assuming we merge tomorrow) on this metadata block _and_ the filename.

2022-08-25 10:30 UTC, ssurbhi560 commented
> I fixed a little issue with the CI, and added a couple of (optional) suggestions for the text. LGTM!

The commits Jaime made to fix the CI got deleted because of some mess I did with git. Sorry for that; I have pushed those changes again now.

2022-08-25 14:51 UTC, kathatherine requested changes
Looks great! Just make sure those two issues that we closed in the last week are marked as such in the blog.

2022-08-25 14:51 UTC, kathatherine commented on posts/2022-08-19-outreachy-wrap-up-blog-2022.rst
> +7.  `DOC: Update documentation about tokens (#1532) <https://github.com/conda-forge/conda-forge.github.io/issues/1532>`__. Working on this `#1793 <https://github.com/conda-forge/conda-forge.github.io
```suggestion
7.  `DOC: Update documentation about tokens (#1532) <https://github.com/conda-forge/conda-forge.github.io/issues/1532>`__. Closed with `#1793 <https://github.com/conda-forge/conda-forge.github.io/pull/1793>`__.
```

2022-08-25 14:51 UTC, kathatherine commented on posts/2022-08-19-outreachy-wrap-up-blog-2022.rst
> +10. `Add a section in docs on security aspects of conda-forge (#1808) <https://github.com/conda-forge/conda-forge.github.io/issues/1808>`__. Working on this `#1812 <https://github.com/conda-forge/con
```suggestion
10. `Add a section in docs on security aspects of conda-forge (#1808) <https://github.com/conda-forge/conda-forge.github.io/issues/1808>`__. Closed with `#1812 <https://github.com/conda-forge/conda-forge.github.io/pull/1812>`__.
```

2022-08-26 15:12 UTC, kathatherine approved these changes
LGTM!

2022-08-26 16:52 UTC, kathatherine commented
@beckermr @jaimergp Shall we go ahead and merge this?

2022-08-26 16:55 UTC, merged

2022-08-26 17:09 UTC, jakirkham commented
Thanks Surbhi! Also thanks all for reviewing 🙏

2022-08-26 17:12 UTC, jakirkham commented
cc @tnabtaf (for awareness)

2022-08-26 17:24 UTC, jakirkham commented
Noticed a small formatting thing. Submitted PR ( https://github.com/conda-forge/blog/pull/58 ) to adjust that